### ISSUE TITLE
use Efaker/FakerAndroid 

### ISSUE THREAD

**Issue by lxyMiao** [khanhduytran0/exagear_windows_emulator#3]
I tried use https://github.com/Efaker/FakerAndroid to modify exagearXserver and it ran successfully

**Comment by seisdr** [comment]
nice

**Comment by ZhymabekRoman** [comment]
Wooow! Nice, We are waiting for hardware acceleration in Exagear !

**Comment by PHANTOMXOTIC** [comment]
PHANTOM XOTIC
